# Site settings
baseurl = "https://zclab.github.io/tikz/"
languageCode = "en-us"
title = "My Favorite Tikz Library"
themesDir = "./themes/"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "../docs" # we go one level up to store site for GitHub pages

[params]
# Meta
title = "zclab · My Favorite Tikz Library"
subtitle = "Favorite Tikz graphics"
author = "Collected from the world"
description = "some modified and commented"
keywords = "LaTeX, TikZ, graphics, favorites"

# Body background color
bodybgcolor = "#f9f9f9"

# Preview container button text
buttontext = "Check the code on GitHub"

# Footer text
footertext = "Template made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [Hugo](http://gohugo.io) and [Aerohub](https://github.com/aerohub)"

# add extra-css
# custom_css = ['css/extra1.css', 'css/extra2.css']
